# Generated by Django 5.1 on 2025-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
